export * from './IGenericRepository';
export * from './IAnswerRepository';
export * from './IQuestionRepository';
export * from './IUserRepository';
export * from './ITagRepository';
export * from './IDislikeAnswer.repository';
export * from './IDislikeQuestionRepositry';
export * from './ILikeAnswerRepository';
export * from './ILikeQuestionRepository';